theme: minima
title: My Firsts Steps in Github Pages
author: Marcos Padilla Herrera
email: alu0101045177@ull.edu.es
description: > # this means to ignore newlines until "baseurl:"
  This is a website for introducing my self to Github Pages

# social links
github_username: marcosph-hub

show_excerpts: true # set to false to remove excerpts on the homepage
